[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm run start"
  targetPort = 3000
  port = 8888
  publish = "build"
  autoLaunch = true
  framework = "#custom"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 