[build]
  command = "CI=false npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "build"
  autoLaunch = true
  framework = "#custom"

[build.environment]
  CI = "false"
  NODE_VERSION = "16"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 